update.packages(ask = FALSE)
install.packages("tidyr")
install.packages("foreach")
install.packages("iterators")
install.packages("snow")
install.packages("doSNOW")
install.packages("conclust")
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("org.Sc.sgd.db", update = TRUE, ask = FALSE)
BiocManager::install("networkBMA", update = TRUE, ask = FALSE)
BiocManager::install("gelnet", update = TRUE, ask = FALSE)
BiocManager::install("iRafNet", update = TRUE, ask = FALSE)
install.packages("mice")
install.packages("DMwR")
install.packages("reshape2")
install.packages("precrec")
install.packages("glmnet")
install.packages("boot")
install.packages("doRNG")
install.packages("dplyr")
install.packages("relaimpo")

BiocManager::install("Biostrings")
install.packages("seqinr")
install.packages("protr")
install.packages("ISLR")
install.packages("e1071")
install.packages("caret")
